let dados = [
    {
        nome: "Adão",
        significado: "Homem, terra",
        local: "Jardim do Éden" ,
        descricao: "Primeiro homem criado por Deus, pai da humanidade." ,
        titulo: "Cultivador, zelador, jardineiro, entre outras atribuições." ,
        papel: "Líder da família",
        familia: "Esposo de Eva, pai de Caim e Abel" ,
        eventos: "Expulsão do Jardim do Éden" ,
        Licoes: "A importância da obediência a Deus, as consequências do pecado." ,
        conexoes: "Referenciado em todo o Antigo Testamento como o primeiro homem." ,
        Observacoes: "" ,
    },   
    {
        nome: "Eva",
        significado: "Vida",
        local: "Jardim do Éden" ,
        descricao: "Primeira mulher, criada a partir de Adão, mãe da humanidade." ,
        titulo: "Ajudante, Companheira." ,
        papel:"Esposa, mãe",
        familia: "Esposa de Adão, mãe de Caim, Abel e Sete." ,
        eventos: "Tentação e queda, maternidade." ,
        Licoes: "A importância da escolha, as consequências do pecado." ,
        conexoes: "Referenciada em todo o Antigo Testamento como a primeira mulher." ,
        Observacoes: "" ,
    },
    {
        nome: "Caim",
        significado: "Aquisição",
        local: "Fora do Jardim do Éden" ,
        descricao: "Primeiro filho de Adão e Eva, conhecido por matar seu irmão Abel por inveja." ,
        titulo:"Sem informações",
        papel:"Agricultor",
        familia: "Filho de Adão e Eva, irmão de Abel." ,
        eventos: "Assassinato de Abel, marca de Caim." ,
        Licoes: "Os perigos da inveja, a importância do perdão." ,
        conexoes: "Referenciado em todo o Antigo Testamento como um exemplo de pecado e violência." ,
        Observacoes: "" ,
    },
    {
        nome: "Abel",
        significado: "Vaidade, futilidade",
        local: "Fora do Jardim do Éeden" ,
        descricao: "Segundo filho de Adão e Eva, pastor que ofereceu um sacrifício agradável a Deus." ,
        titulo: "" ,
        papel: "Pastor" ,
        familia: "Filho de Adão e Eva, irmão de Caim." ,
        eventos: "Oferta rejeitada por Caim, assassinato." ,
        Licoes: "A importância da fé, a justiça divina." ,
        conexoes: "Referenciado em todo o Antigo Testamento como um exemplo de justiça e fé." ,
        Observacoes: "" ,
    },
    {
        nome: "Sete",
        significado: "Posto em lugar de",
        local: "Fora do Jardim do Éden" ,
        descricao: "Filho de Adão e Eva, nascido após a morte de Abel, considerado um substituto para Abel." ,
        titulo: "Sem informações" ,
        papel: "Agricultor/Pastor",
        familia: "Filho de Adão e Eva, irmão de Caim e Abel" ,
        eventos: "Nascimento após a morte de Abel, continuação da linhagem humana." ,
        Licoes: "A esperança em meio à dor, a importância da família." ,
        conexoes: "" ,
        Observacoes: "" ,
        },    
        {
            nome: "Enoque",
            significado: "Dedicado, consagrado",
            local: "Sem informações.",
            descricao: "Descendente de Sete, conhecido por andar com Deus e ser levado por Ele sem ver a morte." ,
            titulo: "Aquele que andou com Deus",
            papel: "Profeta" ,
            familia: "Filho de Jared, pai de Matusalém." ,
            eventos: "Caminhada com Deus, transladação." ,
            Licoes: "A importância da fé e da vida justa, a esperança na vida eterna." ,
            conexoes: "Mencionado em Hebreus 11:5 como exemplo de fé." ,
            Observacoes: "Um dos poucos personagens bíblicos que não morreram, mas foram levados por Deus." ,
            },
        ];
